### ISSUE TITLE
animation autostart doesn't work properly

### ISSUE THREAD

**Issue by icelsj** [MengTo/Spring#23]
a noticed autostart issue found that running on device (I'm tested on iPhone 6 Plus and 5s).
The animation is start properly once the page appeared when we are running using xCode.
If we stop running from xCode, kill the app on phone and restart the app, the animation will not appeared.

unless there is a delayed set on autostart which is more than 0.3

**Comment by MengTo** [comment]
Thanks for the feedback. Is this on the initial view controller? I may be wrong but maybe sometimes the first screen loads a bit too fast sometimes for the animation to be seen. Let me see if I can find a solution.

**Comment by MengTo** [comment]
Okay, I did some more tests. This is a very strange issue since it only happens when:

1) Initial View Controller.
2) Running on the Phone.
3) After app restart, which makes it very hard to debug since it get disconnected from Xcode.

The only workaround I found was to set the delay to 0.5.
Of course, that may make your tests in iOS simulator and Xcode-connected iPhone look different, but I believe the end result (after restart), is what everyone else will see.

Another solution is to avoid using animation in the first view controller, but I guess that depends on what you're trying to do.

Would love to get help on this issue!

**Comment by jamztang** [comment]
It happens that the App has different life cycle when attaching to Debugger.

It results in `Spring.customDidMoveToWindow()` being called before `UIApplication.sharedApplication().applicationState` became `.Active`.

This leads to incorrect behaviour in UIView animation methods, and the duration is not obeyed. `resetAll()` is being called in no time, hence the animation couldn't be seen

I'm working on a solution relying on `UIApplicationDidBecomeActiveNotification`.

**Comment by MengTo** [comment]
Just tried @jamztang 's solution and it worked. Good job James!
