### ISSUE TITLE
Designable: Build Fail

### ISSUE THREAD

**Issue by ervintwj** [MengTo/Spring#283]
I just bought your book and going through v1. Great job, and so far so good.

I do have an issue with Spring though. I've installed through dragging it into xCode and have checked both "copy files if required" and "create group". But, when I try to use it, it says Designable: Build Fail. I've tried your test SpringApp, and it worked, but not for my own app that I'm building. Any idea? 

@MengTo

**Comment by MengTo** [comment]
Sometimes, Xcode needs a bit of time to install libraries correctly, so I
suggest doing some Cmd+Shift+K. If that doesn’t work, try restart Xcode.
And if that doesn’t work, then I’d just download the Xcode project provided
and start from there.

Thanks,
Meng

On October 12, 2017 at 4:38:12 PM, ervintwj (notifications@github.com)
wrote:

I just bought your book and going through v1. Great job, and so far so good.

I do have an issue with Spring though. I've installed through dragging it
into xCode and have checked both "copy files if required" and "create
group". But, when I try to use it, it says Designable: Build Fail. I've
tried your test SpringApp, and it worked, but not for my own app that I'm
building. Any idea?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MengTo/Spring/issues/283>, or mute the thread

**Comment by ervintwj** [comment]
Yeah I've tried cleaning and restarting xCode. Pretty weird though, but thanks.

**Comment by phaiderh** [comment]
@MengTo 

I have the same problem, I tried to clean, restart, but without any luck. It's still not working with me!

Thanks,
Haider

**Comment by ervintwj** [comment]
Sorry @phaiderh, I'm still having the same problem. Can't help here.

**Comment by ervintwj** [comment]
Hey @phaiderh, I might have found an interim solution. I tried placing the Spring folder in the same level as "Supporting Files" instead of under the project folder.

**Comment by MerinoA** [comment]
This issue is solvable by updating the build settings of spring's swift version to swift 4.

<img width="788" alt="screen shot 2017-11-19 at 1 16 58 am" src="https://user-images.githubusercontent.com/7399893/32989274-f7cd0e04-ccc7-11e7-886b-7cfa39ab3937.png">
