### ISSUE TITLE
animation for toolbar bar button item

### ISSUE THREAD

**Issue by omidkh68** [MengTo/Spring#46]
hi everyone, how can I add animations for toolBar and navigationBar bar button item?

**Comment by schneiderandre** [comment]
Unfortunately this is not possible. Every control must conform to the `Springable`protocol. Since `UIBarButtonItem`is not a View and inherits From `UIBarItem -> NSObject`it doesn't have the necessary properties like `layer`and `transform`.

But If you want to use it in your NavigationController, you can nest a regular UIButton inside an UIBarButtonItem.

**Comment by omidkh68** [comment]
@schneiderandre : so how this is possible to do?
