### ISSUE TITLE
DesignableView Build failed

### ISSUE THREAD

**Issue by neohang** [MengTo/Spring#58]
Latest Xcode 6.2 with iOS SDK 8.3
View as iOS 7.0 and Later
![2015-04-10 3 45 07](https://cloud.githubusercontent.com/assets/7413827/7083804/a217278e-df98-11e4-9ba6-61aae0fde749.png)

**Comment by MengTo** [comment]
Thanks for the report, looking into it.

**Comment by MengTo** [comment]
Okay, found the solution. Make sure to check "Create groups". 
![xcode](https://cloud.githubusercontent.com/assets/1065452/7084589/c9db3024-dfa9-11e4-9fcb-b3324d447d98.png)

The folder becomes yellow instead of green.
![screen shot 2015-04-10 at 5 47 16 pm](https://cloud.githubusercontent.com/assets/1065452/7084594/cf4e2f48-dfa9-11e4-9e4b-92c81d990fed.png)

**Comment by neohang** [comment]
Problem solved! Well done~
