### ISSUE TITLE
AllowUserInteraction during animations

### ISSUE THREAD

**Issue by b354c502** [MengTo/Spring#66]
Currently, user interaction on SpringViews being animated is disabled... ie, they don't respond to touch events during the animation.  To remedy this, the getAnimationOptions() function needs to be modified with something like: return UIViewAnimationOptions.CurveEaseIn | UIViewAnimationOptions.AllowUserInteraction   (for each case)

See the first answer regarding this here: http://stackoverflow.com/questions/3614116/uiscrollview-touch-events-during-animation-not-firing-with-animatewithduration

**Comment by schneiderandre** [comment]
Good point :+1:, I think this could be an additional `IBInspectable`.

**Comment by schneiderandre** [comment]
We can easily add user interaction for all view animations, but most of the animation presets are directly applied to the layer with `CAAnimation`.
We can't easily interact with these layer animations, because the view itself is always positioned on the same position while the layer moves. You can do a hit test on the provided `presentationLayer` which represents the state of the layer as it currently appears onscreen.

We can include the possibility to interact with views during view animations, however I would suggest to implement hit testing (which is needed for `CAAnimations`) outside of the Spring framework.
